name: Demo_stage_Step Function

on:
  push:
    branches:
      - main
    paths:
      - 'nodiejs_demo_1/src/demo.json'

jobs:
  update-step-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAZNJ5QUNOQ4XJWMVK
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Update Step Function Definition
        run: |
          pwd
          ls -al
          aws stepfunctions update-state-machine \
          --state-machine-arn arn:aws:states:us-east-1:647058465629:stateMachine:demo-sf \
          --definition file://nodiejs_demo_1/src/demo.json
