name: Demo_stage_Step Function

on:
  push:
    branches:
      - main
    paths:
      - 'nodiejs_demo_1/src/deploy.json'

jobs:
  update-step-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1

      - name: Update Step Function Definition
        run: |
          pwd
          ls -al
          aws stepfunctions update-state-machine \
          --state-machine-arn arn:aws:states:us-east-1:647058465629:stateMachine:demo-sf \
          --definition file://nodiejs_demo_1/src/demo.json
