name: Demo_stage_Step Function

on:
  push:
    branches:
      - main
    paths:
      - 'nodiejs_demo_1/src/demo.json'

jobs:
  update-step-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Step Function Definition
        run: |
          # Get the current date and time in the format "YYYY-MM-DD_HH:MM:SS"
          VERSION_DESCRIPTION=$(date '+%Y-%m-%d_%H:%M:%S')

          # Update state machine with new definition and publish a new version
          aws stepfunctions update-state-machine \
            --state-machine-arn arn:aws:states:us-east-1:647058465629:stateMachine:demo-sf \
            --definition file://nodejs_demo_1/src/demo.json \
            --publish publish=true \
            --version-description "$VERSION_DESCRIPTION"
